server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # API application logs
  - job_name: kaopizauth-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: kaopizauth-api
          environment: ${ENVIRONMENT:-production}
          __path__: /var/log/api/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: "@t"
            level: "@l"
            message: "@m"
            exception: "@x"
            request_id: RequestId
            user_id: UserId
            duration: Duration
      
      - timestamp:
          source: timestamp
          format: RFC3339
      
      - labels:
          level:
          request_id:
          user_id:

  # WebApp logs
  - job_name: kaopizauth-webapp
    static_configs:
      - targets:
          - localhost
        labels:
          job: kaopizauth-webapp
          environment: ${ENVIRONMENT:-production}
          __path__: /var/log/webapp/*.log

  # Nginx access logs
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          environment: ${ENVIRONMENT:-production}
          __path__: /var/log/nginx/access.log

    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>[\d\.]+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<request>[^"]*)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)" "(?P<http_x_forwarded_for>[^"]*)" rt=(?P<request_time>[\d\.]+) uct="(?P<upstream_connect_time>[^"]*)" uht="(?P<upstream_header_time>[^"]*)" urt="(?P<upstream_response_time>[^"]*)"'
      
      - labels:
          remote_addr:
          status:
          request_time:
      
      - metrics:
          request_duration_seconds:
            type: Histogram
            description: "Duration of HTTP requests"
            source: request_time
            config:
              buckets: [0.1, 0.5, 1.0, 2.0, 5.0]
          
          http_requests_total:
            type: Counter
            description: "Total number of HTTP requests"
            config:
              action: inc

  # Nginx error logs
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          environment: ${ENVIRONMENT:-production}
          __path__: /var/log/nginx/error.log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<pid>\d+)#(?P<tid>\d+): (?P<message>.*)'
      
      - timestamp:
          source: timestamp
          format: "2006/01/02 15:04:05"
      
      - labels:
          level:
          pid: