name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '20.x'

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: KaopizAuthTest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=KaopizAuthTest;Username=postgres;Password=password"

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: src/KaopizAuth.WebApp/package-lock.json

    - name: Install dependencies
      working-directory: src/KaopizAuth.WebApp
      run: npm ci

    - name: Type check
      working-directory: src/KaopizAuth.WebApp
      run: npm run type-check

    - name: Lint code
      working-directory: src/KaopizAuth.WebApp
      run: npm run lint

    - name: Build application
      working-directory: src/KaopizAuth.WebApp
      run: npm run build

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Check for vulnerable packages
      run: dotnet list package --vulnerable --include-transitive || exit 0

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend, security-scan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta-api
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}-api
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha

    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.api
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Extract metadata for WebApp
      id: meta-webapp
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}-webapp
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha

    - name: Build and push WebApp image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.webapp
        push: true
        tags: ${{ steps.meta-webapp.outputs.tags }}
        labels: ${{ steps.meta-webapp.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}
        
    - name: Deploy to staging server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} << 'EOF'
          set -e
          
          # Navigate to application directory
          cd /opt/kaopizauth
          
          # Create backup before deployment
          docker-compose -f docker-compose.staging.yml exec -T kaopizauth-db \
            pg_dump -U postgres KaopizAuth > /backups/pre_deploy_$(date +%Y%m%d_%H%M%S).sql || true
          
          # Pull latest images
          docker-compose -f docker-compose.staging.yml pull
          
          # Run database migrations
          docker-compose -f docker-compose.staging.yml run --rm kaopizauth-api \
            dotnet ef database update --no-build
          
          # Restart services with zero downtime
          docker-compose -f docker-compose.staging.yml up -d --remove-orphans
          
          # Wait for health check
          sleep 30
          curl -f http://localhost/api/health || exit 1
          
          echo "Staging deployment completed successfully"
        EOF

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.PRODUCTION_SSH_KEY }}
        
    - name: Deploy to production server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} << 'EOF'
          set -e
          
          # Navigate to application directory
          cd /opt/kaopizauth
          
          # Create pre-deployment backup
          echo "Creating pre-deployment backup..."
          docker-compose -f docker-compose.production.yml exec -T kaopizauth-db \
            pg_dump -U postgres KaopizAuth | gzip > /backups/pre_deploy_$(date +%Y%m%d_%H%M%S).sql.gz
          
          # Pull latest images
          echo "Pulling latest images..."
          docker-compose -f docker-compose.production.yml pull
          
          # Run database migrations with rollback capability
          echo "Running database migrations..."
          docker-compose -f docker-compose.production.yml run --rm \
            -v $(pwd)/scripts:/scripts \
            kaopizauth-api /scripts/migrate.sh
          
          # Blue-green deployment simulation
          echo "Starting blue-green deployment..."
          
          # Scale up new instances
          docker-compose -f docker-compose.production.yml up -d --scale kaopizauth-api=2
          
          # Wait for new instances to be healthy
          sleep 60
          for i in {1..10}; do
            if curl -f http://localhost/api/health; then
              echo "Health check passed"
              break
            fi
            echo "Waiting for application to be healthy... ($i/10)"
            sleep 10
          done
          
          # Remove old instances
          docker-compose -f docker-compose.production.yml up -d --remove-orphans
          
          # Final health check
          if ! curl -f http://localhost/api/health; then
            echo "Final health check failed, rolling back..."
            # Rollback logic would go here
            exit 1
          fi
          
          # Clean up old images
          docker image prune -f
          
          echo "Production deployment completed successfully"
        EOF
        
    - name: Notify deployment success
      if: success()
      run: |
        echo "Production deployment successful"
        # Add notification logic here (Slack, email, etc.)
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "Production deployment failed"
        # Add notification logic here (Slack, email, etc.)

  security-scan-production:
    name: Production Security Scan
    runs-on: ubuntu-latest
    needs: deploy-production
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      run: |
        # Add security scanning tools here
        echo "Running security scans..."
        
    - name: Container security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}-api:main'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload security scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'